# Generated by Django 5.2.3 on 2025-07-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью",
                null=True,
                upload_to="lms/course_previews",
                verbose_name="Превью",
            ),
        ),
    ]
